"""tables

Revision ID: cc65efa29843
Revises:
Create Date: 2024-06-18 16:41:01.644359

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cc65efa29843"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team",
        sa.Column("football_api_team_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("football_api_team_id"),
    )
    op.create_table(
        "user",
        sa.Column("telegram_api_user_id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("username", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("telegram_api_user_id"),
    )
    op.create_table(
        "draw",
        sa.Column("telegram_api_user_id", sa.BigInteger(), nullable=False),
        sa.Column("football_api_team_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["football_api_team_id"],
            ["team.football_api_team_id"],
        ),
        sa.ForeignKeyConstraint(
            ["telegram_api_user_id"],
            ["user.telegram_api_user_id"],
        ),
        sa.PrimaryKeyConstraint("telegram_api_user_id", "football_api_team_id"),
    )
    op.create_table(
        "fixture",
        sa.Column("football_api_fixture_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("home_team_football_api_team_id", sa.Integer(), nullable=False),
        sa.Column("away_team_football_api_team_id", sa.Integer(), nullable=False),
        sa.Column("home_team", sa.String(), nullable=False),
        sa.Column("away_team", sa.String(), nullable=False),
        sa.Column("home_team_goals", sa.Integer(), nullable=True),
        sa.Column("away_team_goals", sa.Integer(), nullable=True),
        sa.Column("home_team_winner", sa.Boolean(), nullable=True),
        sa.Column("away_team_winner", sa.Boolean(), nullable=True),
        sa.Column("kick_off", sa.DateTime(timezone=True), nullable=False),
        sa.Column("venue_city", sa.String(), nullable=False),
        sa.Column("venue_name", sa.String(), nullable=False),
        sa.Column("round", sa.String(), nullable=False),
        sa.Column("home_goals_half_time", sa.Integer(), nullable=True),
        sa.Column("away_goals_half_time", sa.Integer(), nullable=True),
        sa.Column("home_goals_full_time", sa.Integer(), nullable=True),
        sa.Column("away_goals_full_time", sa.Integer(), nullable=True),
        sa.Column("away_goals_extra_time", sa.Integer(), nullable=True),
        sa.Column("home_goals_extra_time", sa.Integer(), nullable=True),
        sa.Column("home_goals_penalties", sa.Integer(), nullable=True),
        sa.Column("away_goals_penalties", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["away_team_football_api_team_id"],
            ["team.football_api_team_id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_football_api_team_id"],
            ["team.football_api_team_id"],
        ),
        sa.PrimaryKeyConstraint("football_api_fixture_id"),
    )
    op.create_table(
        "player",
        sa.Column("football_api_player_id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("football_api_team_id", sa.Integer(), nullable=False),
        sa.Column("yellow_cards", sa.Integer(), nullable=True),
        sa.Column("yellow_then_red_cards", sa.Integer(), nullable=True),
        sa.Column("red_cards", sa.Integer(), nullable=True),
        sa.Column("goals", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["football_api_team_id"],
            ["team.football_api_team_id"],
        ),
        sa.PrimaryKeyConstraint("football_api_player_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player")
    op.drop_table("fixture")
    op.drop_table("draw")
    op.drop_table("user")
    op.drop_table("team")
    # ### end Alembic commands ###
