import random


def get_insult() -> str:
    return random.choice(INSULTS)


INSULTS = [
    "abomination",
    "abshole",
    "absolute zero",
    "accident",
    "acrotomophile",
    "addle-brain",
    "addle head",
    "addle pate",
    "a-hole",
    "airhead",
    "alcatote",
    "anarchist",
    "animal",
    "animal food trough wiper",
    "anorak",
    "antilesbian",
    "anus",
    "anushole",
    "anus licker",
    "ape",
    "apefucker",
    "arse",
    "arsebadger",
    "arsebreath",
    "arseface",
    "arsehole",
    "arse-licker",
    "ass",
    "assaholic",
    "ass bag",
    "ass bitch",
    "ass clown",
    "asscunt",
    "assface",
    "assfucker",
    "asshat",
    "asshole",
    "asshole licker",
    "ass-kisser",
    "ass licker",
    "ass master",
    "assmonkey",
    "assmouth",
    "assmunch",
    "ass-nugget",
    "ass rammer",
    "ass sucker",
    "asstard",
    "asswagon",
    "assweed",
    "asswhore",
    "asswipe",
    "aunt fucker",
    "autofellator",
    "baboon",
    "baby",
    "baby butcher",
    "baby maker",
    "backstabber",
    "backwoodsman",
    "badass",
    "badasshole",
    "bad bitch",
    "bad boy",
    "baddie",
    "baddy",
    "bad friend",
    "badgerfucker",
    "bad girl",
    "bad guy",
    "bad nut",
    "bad squishies",
    "bad squishy",
    "baduns",
    "bag of dicks",
    "bag of hammers",
    "bag whore",
    "ballkicker",
    "ball licker",
    "ball of rage",
    "balloon head",
    "ballsack",
    "bandit",
    "bangsat",
    "barbarian",
    "Barbie-fucker",
    "barnacle head",
    "bashful Beethoven",
    "basshole",
    "bastard",
    "bawbag",
    "bawtboy",
    "bayard",
    "bean head",
    "bear",
    "beast",
    "beast of burden",
    "beaver",
    "Becky",
    "bedwetter",
    "beetlehead",
    "beggar",
    "beginner",
    "belch",
    "beldame",
    "bell-end",
    "belly button",
    "belly-god",
    "belly itcher",
    "berk",
    "bespawler",
    "beta",
    "beta cuck",
    "biatch",
    "bimbo",
    "biopirate",
    "birdbrain",
    "birdfucker",
    "bish",
    "bitch",
    "bitch-ass",
    "bitch boy",
    "bitchcunt",
    "bitchface",
    "bitchfucker",
    "bitchtits",
    "bitchwad",
    "bitchwhore",
    "bitchzilla",
    "biter",
    "biznatch",
    "blabbermouth",
    "blackguard",
    "blaggard",
    "bleeder",
    "blockhead",
    "bloodsucker",
    "blubber butt",
    "blubber gut",
    "bludger",
    "blue meanie",
    "bluntie",
    "bobchin",
    "body-shamer",
    "body snatcher",
    "bogeyman",
    "bonehead",
    "boob",
    "booby",
    "booby turds",
    "booger",
    "booger brain",
    "boomer",
    "bootlicker",
    "booty",
    "boozer",
    "bot",
    "box of dildos",
    "boyfucker",
    "bozo",
    "brainlet",
    "brat",
    "bratface",
    "breeder",
    "brickfucker",
    "brickhead",
    "brotherfucker",
    "brown nose",
    "brown noser",
    "brute",
    "bubbler",
    "buffoon",
    "bugfucker",
    "bugger",
    "bull",
    "bull dyke",
    "bullfuck",
    "bully",
    "bullyman",
    "bum",
    "bumbo",
    "bum chum",
    "bum-fucker",
    "bum head",
    "bunghole",
    "bungholio",
    "burden",
    "burp",
    "butt",
    "buttass",
    "buttbreath",
    "butt cough",
    "butterhead",
    "buttface",
    "butt farter",
    "buttfucker",
    "butthead",
    "butthole",
    "butt hunter",
    "buttkisser",
    "buttknocker",
    "butt knuckler",
    "buttlicker",
    "butt-lord",
    "buttmunch",
    "butt nugget",
    "butt pirate",
    "butt sniffer",
    "butt tickler",
    "buttwad",
    "butt-wipe",
    "cack",
    "cad",
    "camelfucker",
    "candyass",
    "cannibal",
    "carny",
    "carpet muncher",
    "carton girl",
    "cat",
    "catfucker",
    "catnapper",
    "caveman",
    "chauvinist",
    "chav",
    "cheater",
    "cheese sucker",
    "chicken",
    "chickenfucker",
    "chickenhawk",
    "chicken shit",
    "childfucker",
    "child predator",
    "chill girl",
    "chit",
    "choad",
    "chomo",
    "chubby chaser",
    "chucklehead",
    "chump",
    "churl",
    "clart",
    "clit",
    "clitbag",
    "clithead",
    "clit spasm",
    "clod",
    "clown",
    "clunge",
    "cock",
    "cockalorum",
    "cockbite",
    "cockboy",
    "cockburger",
    "cockfucker",
    "cockhead",
    "cock holster",
    "cock-juggling thunder cunt",
    "cockmaster",
    "cocknose",
    "cockroach",
    "cocksucker",
    "cocktease",
    "cockwaddle",
    "cockweasel",
    "cockwomble",
    "coffee-snob",
    "commie",
    "common mobile vulgaris",
    "common sneak theif",
    "con man",
    "con merchant",
    "coochie-ass",
    "coomer",
    "coprophile",
    "corpsefucker",
    "couch potato",
    "cougar",
    "country bumpkin",
    "cousinfucker",
    "cousin humper",
    "cow",
    "coward",
    "cowardy custard",
    "cowfucker",
    "crab",
    "crackhead",
    "crack whore",
    "crap eater",
    "craphole",
    "creep",
    "creeper",
    "cretin",
    "crikey",
    "criminal",
    "crook",
    "crotch",
    "crud",
    "crud head",
    "crybaby",
    "cuck",
    "cuck fluffer",
    "cuckold",
    "culprit",
    "cumbubble",
    "cumbucket",
    "cum burgler",
    "cum dumpster",
    "cumfucker",
    "cum guzzler",
    "cum licker",
    "cumslut",
    "cumstain",
    "cumwipe",
    "cunning linguist",
    "cunt",
    "cuntass",
    "cuntbiscuit",
    "cuntbitch",
    "cuntbreath",
    "cuntface",
    "cunt fart",
    "cuntfucker",
    "cunthead",
    "cuntlicker",
    "cunt muncher",
    "cuntpuddle",
    "cunt rag",
    "cuntshit",
    "cuntsucker",
    "cuntzilla",
    "cuss",
    "custard",
    "daddyfucker",
    "dandiprat",
    "dark prince",
    "daughterfucker",
    "deadhead",
    "degenerate",
    "delinquent",
    "demon",
    "dendrophiliac",
    "der-brain",
    "derp",
    "desperado",
    "devil",
    "devil hooch",
    "devil woman",
    "dick",
    "dickass",
    "dickbag",
    "dickbreath",
    "dickcheese",
    "dickface",
    "dickfart",
    "dickfucker",
    "dickhead",
    "dickhole",
    "dickless",
    "dicklicker",
    "dick man",
    "dick mouth",
    "dickshitter",
    "dick sniffer",
    "dicksplash",
    "dick-sucker",
    "dicktard",
    "dicktator",
    "dicktits",
    "dickwad",
    "dickweasel",
    "dickweed",
    "dildo",
    "dillhole",
    "dill pickle",
    "dim bulb",
    "dimmadumbass",
    "dimwit",
    "ding-a-ling",
    "ding-dong",
    "ding-head",
    "dingleberry",
    "dinglebop",
    "dingus",
    "dinosaur",
    "dipass",
    "dipfuck",
    "dipshit",
    "dipstick",
    "dirtbag",
    "dirtbrain",
    "dirthead",
    "dirt muncher",
    "dirtwad",
    "dirty bunch",
    "discord mod",
    "disgrace",
    "div",
    "diversity hire",
    "divvy",
    "dodo",
    "dog",
    "dogbolt",
    "dogbreath",
    "dogfucker",
    "dognapper",
    "dolt",
    "donk",
    "donkey",
    "donkey dick",
    "donkeyfucker",
    "donkeyhole",
    "doodle",
    "doofus",
    "dookie",
    "dope",
    "dopester",
    "dote",
    "dotterel",
    "douche",
    "douche bag",
    "doucheburger",
    "douche canoe",
    "douchefag",
    "douchelord",
    "douche nark",
    "douche nozzle",
    "douchewad",
    "douchewagon",
    "dracula",
    "dragon",
    "dreamer",
    "drip",
    "drug addict",
    "druggie",
    "druggy",
    "drunkard",
    "duckfucker",
    "dude",
    "dullard",
    "dumbarse",
    "dumbass",
    "dumbbell",
    "dumb blonde",
    "dumb fucker",
    "dumbo",
    "dum-dum",
    "dummy",
    "dunce",
    "duncebucket",
    "dunderhead",
    "dupe",
    "dweeb",
    "dweebling",
    "dyke",
    "earthworm",
    "ecocrazy",
    "ecofreak",
    "ecohippie",
    "edgelord",
    "egghead",
    "egohead",
    "egotist",
    "emo",
    "enviro",
    "envirotard",
    "eunuch",
    "evildoer",
    "fag",
    "faggot",
    "fag tits",
    "failed abortion",
    "failure",
    "fairy",
    "faker",
    "fakkfish",
    "fanny",
    "fannyflaps",
    "fantasshole",
    "farmer",
    "fart",
    "fart balls",
    "fart boy",
    "fartbutt",
    "farter",
    "fartface",
    "farthead",
    "fart hole",
    "fartknocker",
    "fartman",
    "fart smeller",
    "fart sucker",
    "fascist",
    "fatass",
    "fat boy",
    "fatface",
    "fatfuck",
    "fat geeze",
    "fat geezer",
    "fathead",
    "fatherfucker",
    "fatherless",
    "fatso",
    "fat-tard",
    "fatty",
    "fauxman",
    "Feetlicks",
    "fellow",
    "fembot",
    "fenderhead",
    "fetus",
    "fib",
    "fibber",
    "fiddle",
    "fiddler",
    "fiend",
    "filth",
    "fink",
    "Fiona",
    "first time skier",
    "fish",
    "fish fucker",
    "fish killer",
    "fishwife",
    "fixer",
    "flag fucker",
    "flake",
    "flameout",
    "flange",
    "flat-earther",
    "flatfoot",
    "flatterer",
    "fleabag",
    "flip-flopper",
    "fluffy",
    "fon",
    "food snobs",
    "fool",
    "foot-licker",
    "foreskin ripper",
    "forty year old woman",
    "foul mouth",
    "four eyes",
    "fraggle",
    "fraidy cat",
    "frat-boy bitch",
    "fraud",
    "freak",
    "freeloader",
    "friend of Dorothy",
    "fruit",
    "fruitcake",
    "frump",
    "fuck",
    "fuckass",
    "fuckbait",
    "fuckboy",
    "fuckbucket",
    "fucker",
    "fuckface",
    "fuckhead",
    "fuckhole",
    "fucklord",
    "fuck noggin",
    "fucknose",
    "fucknozzle",
    "fuck nugget",
    "fuckrod",
    "fuckshit",
    "fuckskull",
    "fuckstain",
    "fuckster",
    "fucktard",
    "fucktoy",
    "fuck trumpet",
    "fuckweasel",
    "fuckwhistle",
    "fuckwit",
    "fudge packer",
    "fudger",
    "fugly",
    "funpire",
    "furry",
    "futanari",
    "fuzznut",
    "gadfly",
    "gangster",
    "gaper",
    "garbage",
    "gawk",
    "gaytard",
    "gaywad",
    "geck",
    "geebag",
    "geek",
    "gentleman",
    "gestator",
    "gig",
    "gimp",
    "ginger",
    "gink",
    "girl",
    "girly",
    "git",
    "glut",
    "glut of tv",
    "glutton",
    "glutton for punishment",
    "goblin",
    "gobshite",
    "gold digger",
    "goober",
    "good-for-nothing",
    "goody-goody",
    "Goody Two-Shoes",
    "goof",
    "goofball",
    "goofy",
    "goon",
    "goontard",
    "goose",
    "gooseberry",
    "GoPro Kid",
    "gorilla",
    "gowk",
    "grammar cop",
    "grammar Nazi",
    "grammar police",
    "grandfatherfucker",
    "grandmotherfucker",
    "granny",
    "gravy face",
    "greeniac",
    "grimalkin",
    "grinch",
    "gronk",
    "grouch",
    "grumpy",
    "gubbins",
    "gump",
    "guttermouth",
    "hamster",
    "handfucker",
    "ha'p'orth",
    "hater",
    "headass",
    "he-bitch",
    "helldog",
    "hikikomori",
    "hilding",
    "hillbilly",
    "hippie",
    "Hismomgone",
    "Hitler",
    "Hitlerian",
    "Hitlerite",
    "ho",
    "hoarder",
    "hobbledehoy",
    "hobo",
    "hoe",
    "hog",
    "hoghead",
    "Homer Simpson",
    "homo",
    "homophobe",
    "homophobephobe",
    "honeypot",
    "hoodie",
    "hoodlum",
    "hooker",
    "hooligan",
    "hooplehead",
    "horndog",
    "Hornswaggler",
    "horseface",
    "horsefucker",
    "horse's ass",
    "horse's necktie",
    "hosebag",
    "hoser",
    "human participation award",
    "hussy",
    "hyena",
    "hypocrite",
    "idiot",
    "idiotist",
    "idiot sandwich",
    "idiot savant",
    "idleton",
    "ignoramus",
    "imbecile",
    "inbred",
    "inbreeder",
    "incel",
    "incester",
    "innie",
    "intercourser",
    "jabroni",
    "jackass",
    "jackasshole",
    "jackhole",
    "jackwagon",
    "jagweed",
    "jailbait",
    "jamoke",
    "jeebweezer",
    "jelly",
    "jelly belly",
    "jelly roll",
    "jerk",
    "jerkoff",
    "jerkwad",
    "jerk water",
    "jerkweed",
    "Jesus freak",
    "jit stain",
    "jizzbreath",
    "jizzcock",
    "jizz guzzler",
    "jizz stain",
    "jizzwizard",
    "jock",
    "joker",
    "jokes",
    "jolterhead",
    "jolthead",
    "juggins",
    "junkie",
    "junky",
    "Karen",
    "keener",
    "Ken",
    "Kevin",
    "kevun",
    "keyboard warrior",
    "kiddie fiddler",
    "kiddy fiddler",
    "kidfucker",
    "killjoy",
    "king lesbian",
    "kinkster",
    "klutz",
    "knacker",
    "knee-jerk",
    "knob",
    "knobhead",
    "knobjockey",
    "knucklehead",
    "k-pooper",
    "Kyle",
    "lady of the evening",
    "lamebrain",
    "landwhale",
    "langer",
    "lard",
    "lard butt",
    "lard face",
    "laughing stock",
    "leech",
    "lemon",
    "lesbianist",
    "lesbie",
    "lesbo",
    "lessie",
    "lez",
    "lezbo",
    "lezzer",
    "lezzie",
    "lezzo",
    "lezzy",
    "liar",
    "libtard",
    "lickspittle",
    "little buddy",
    "little puke baby",
    "loafer",
    "lobotomite",
    "lodge rat",
    "loser",
    "Loserface",
    "loudmouth",
    "louse",
    "low-life",
    "lummox",
    "lunatic",
    "lunkhead",
    "lurdane",
    "lush",
    "mackerel",
    "madman",
    "maggot",
    "mamzer",
    "man cunt",
    "man-eater",
    "man-whore",
    "marauder",
    "masochist",
    "meanie",
    "meathead",
    "Meathead Fauncewater",
    "megabitch",
    "megadouche",
    "menstruator",
    "mental midget",
    "midget",
    "Migger",
    "milk chugger",
    "milksop",
    "mime",
    "Mingie",
    "minx",
    "Miss Ann",
    "missing link",
    "mistake",
    "Mister Charlie",
    "mistress of all evil",
    "mobster",
    "mofo",
    "Mohambie",
    "mongoose",
    "mongrel",
    "monkey",
    "monkeyface",
    "monkeyspank",
    "monster",
    "moocher",
    "mooncalf",
    "moron",
    "mother",
    "motherbitch",
    "mother father",
    "motherfucker",
    "mousefucker",
    "mouth breather",
    "Mr. Bungholio",
    "mr hands",
    "Mr. Obsessed",
    "Mrs. Quack-Quack",
    "Mr. Struggle",
    "Mr. Talk",
    "mucky pup",
    "muff diver",
    "mug",
    "muggins",
    "mule",
    "mullet",
    "mullet daddy",
    "mullethead",
    "mumbler",
    "mumpsimus",
    "mung",
    "muppet",
    "mush head",
    "mutant",
    "mutt",
    "mythic bitch",
    "nagger",
    "narcissist",
    "nark",
    "nasty pants",
    "naysayer",
    "nazi",
    "neanderthal",
    "Nebbish",
    "neckbeard",
    "necrophiliac",
    "ne'er-do-well",
    "neet",
    "negative Nancy",
    "nephew fucker",
    "nerf herder",
    "niece fucker",
    "nimrod",
    "nincompoop",
    "ninny",
    "ninnyhammer",
    "nit",
    "nitwit",
    "nobody",
    "non",
    "nonce",
    "noob",
    "noodle",
    "numbnuts",
    "numbskull",
    "numps",
    "numpty",
    "numskull",
    "nupson",
    "nut",
    "nutcase",
    "nutjob",
    "nutsack",
    "oaf",
    "oddball",
    "offender",
    "ogre",
    "oinker",
    "old lady",
    "old man",
    "old woman",
    "oompa loompa",
    "orphan",
    "outcast",
    "outlaw",
    "oxygen thief",
    "pack",
    "packrat",
    "pain",
    "pain in the ass",
    "pain in the butt",
    "pain in the neck",
    "panini head",
    "pansy",
    "parasite",
    "pariah",
    "party pooper",
    "pavement princess",
    "peasant",
    "pedophile",
    "peehole",
    "peeping tom",
    "penchod",
    "pencil dick",
    "penis butt",
    "penis face",
    "Penis licker",
    "penispuffer",
    "penis sucker",
    "perv",
    "pervert",
    "philanderer",
    "phony",
    "pickle-puss",
    "pickpocket",
    "piece of crap",
    "piece of garbage",
    "piece of junk",
    "piece of shit",
    "piece of trash",
    "piece of work",
    "pie hole",
    "pig",
    "pig-dog",
    "pig-farmer",
    "pigfucker",
    "piggy",
    "piggy-wiggy",
    "pig shite",
    "pig-slammer",
    "pig slop",
    "pigslut",
    "pikspiller",
    "pilgarlic",
    "pillock",
    "pimp",
    "pimple",
    "pimple face",
    "pinhead",
    "pirate",
    "pissbaby",
    "pissbrain",
    "pissbreath",
    "pissface",
    "piss gulper",
    "pisshead",
    "pisskidney",
    "piss monkey",
    "piss pig",
    "pisspot",
    "pisswizard",
    "pissy bitch",
    "pizzaface",
    "pleb",
    "plonker",
    "pooface",
    "poohead",
    "poop",
    "poopeater",
    "pooper",
    "poopface",
    "poopfucker",
    "poop hole",
    "pooplicker",
    "poopy head",
    "poopy pants",
    "porno freak",
    "porn star",
    "potato",
    "pothead",
    "potty head",
    "potty mouth",
    "prat",
    "predator",
    "prick",
    "prickface",
    "primadonna",
    "problem",
    "Professor Environment",
    "Professor Environment Pants",
    "Professor Killjoy",
    "prom night dumpster baby",
    "pro skirt",
    "pseudointellectual",
    "psycho",
    "pube flosser",
    "pudding",
    "pudwhacker",
    "puff",
    "puke",
    "puke baby",
    "puke bag",
    "pukeball",
    "pukeface",
    "pulp gulper",
    "pumpkin eater",
    "punk",
    "punkass",
    "punter",
    "puppet",
    "pus licker",
    "pussy",
    "pussyboy",
    "pussyfucker",
    "pussy pisser",
    "pussy sucker",
    "puta",
    "pyramidiot",
    "quack",
    "quat",
    "queef",
    "queef cookie",
    "queer bait",
    "querulant",
    "quim",
    "quitter",
    "raasclaat",
    "rabbitfucker",
    "ranga",
    "rascal",
    "rat",
    "ratcatcher",
    "ratfink",
    "ratfucker",
    "rectal semen splooge",
    "rectal wart",
    "redneck",
    "reject",
    "renegade",
    "reprobate",
    "retard",
    "retarded",
    "riff-raff",
    "riot",
    "roaster",
    "robber",
    "robot",
    "rock whore",
    "rogue",
    "roue",
    "roughneck",
    "rowdy",
    "rudesby",
    "ruffian",
    "rug muncher",
    "ruler of the weak",
    "Rumpleforeskin",
    "runt",
    "sadist",
    "saggy fuck",
    "saprophyte",
    "sausage-masseuse",
    "scaredy-cat",
    "scene boy",
    "schlimazel",
    "schlub",
    "schmo",
    "schmuck",
    "scobberlotcher",
    "scoozie",
    "scoundrel",
    "screw",
    "screw up",
    "scrote",
    "scrotum licker",
    "scrotum-sucker",
    "scuddle butt",
    "scum",
    "scumbag",
    "scumbreath",
    "scumbutt",
    "scumface",
    "scumfuck",
    "scumhead",
    "scumlord",
    "scumwad",
    "scuzzbag",
    "scuzzball",
    "scuzzbucket",
    "scuzzoid",
    "seedling of satan",
    "see you next Tuesday",
    "serf",
    "sewer rat",
    "sex haver",
    "sex maniac",
    "sexter",
    "shark",
    "sharmuta",
    "she-devil",
    "sheepfucker",
    "sheepshagger",
    "she-male",
    "she-ogre",
    "shill",
    "shit",
    "shitass",
    "shitbag",
    "shitball",
    "shitbird",
    "shitbrain",
    "shitbreath",
    "shitbucket",
    "shitbum",
    "shitcunt",
    "shitdick",
    "shite",
    "shit-eater",
    "shitehawk",
    "shitface",
    "shit-for-brains",
    "shitfuck",
    "shitfucker",
    "shitgoblin",
    "shithead",
    "shithouse",
    "shitizen",
    "shitkicker",
    "Shitler",
    "shitlord",
    "shitmagnet",
    "shitneck",
    "shitnugget",
    "shitpicker",
    "shitpiss",
    "shitpot",
    "shitpouch",
    "shitpuddle",
    "shitsack",
    "shitshow",
    "shit sniffer",
    "shit stain",
    "shitter",
    "shitty titty",
    "shitty titty jelly belly",
    "shitweasel",
    "shmekl",
    "show off",
    "shrek",
    "shrew",
    "shuzzbutt",
    "shyster",
    "sibling fucker",
    "sick",
    "silly king-a",
    "simp",
    "simpleton",
    "sissy",
    "sisterfucker",
    "sister humper",
    "skank",
    "sket",
    "skinflint",
    "skirt-chaser",
    "skite",
    "skullfucker",
    "skunk",
    "skunkfucker",
    "slacker",
    "slag",
    "slam-pig",
    "slaphead",
    "slave",
    "slay queen",
    "sleaze",
    "sleazebag",
    "sleazeball",
    "sleazewad",
    "sleeze",
    "sleeze bag",
    "slimeface",
    "slob",
    "slut",
    "slutbag",
    "slutfucker",
    "sluthead",
    "smell-feast",
    "smellfungus",
    "smooth brain",
    "smughead",
    "snail",
    "snake",
    "snapperhead",
    "sneak",
    "sneakerhead",
    "sneak theif",
    "snob",
    "snollygoster",
    "snot",
    "snotball",
    "snotface",
    "snothead",
    "snot nose",
    "snotwad",
    "snowflake",
    "so-and-so",
    "SOB",
    "softhead",
    "son of a biscuit",
    "son of a bitch",
    "son of a bucket",
    "son of a gun",
    "son of a jackal",
    "son of a monkey",
    "son of a motherless goat",
    "son of a mother trucker",
    "son of a nutcracker",
    "Son of a Pup",
    "son of a sea-cook",
    "son of a silly person",
    "son of a whore",
    "son of Lucifer",
    "son of satan",
    "son of stench",
    "son of the devil",
    "sot",
    "sourhead",
    "sourpuss",
    "sow",
    "soy boy",
    "spack",
    "spammer",
    "sped",
    "sphincter",
    "spider",
    "splenetic",
    "splooge moose",
    "sponge",
    "spotted hyena",
    "square",
    "Squeaker",
    "squib",
    "squid brain",
    "stan",
    "stealer",
    "stick in the mud",
    "stink cunt",
    "stinker",
    "stinkhole",
    "Stinky McPoopPants",
    "stone butch",
    "straggot",
    "strawberry",
    "stupidhead",
    "sucker",
    "swindler",
    "swine",
    "swinger",
    "sycophant",
    "tabby cat",
    "taint hair",
    "taint sniffer",
    "tard",
    "tarter",
    "tattletale",
    "teacher's pet",
    "TERF",
    "terrorist",
    "thickhead",
    "thief",
    "Thing One",
    "Thing Two",
    "thot",
    "thotpocket",
    "threat",
    "throat-slitter",
    "thug",
    "thundercunt",
    "tit",
    "titbag",
    "tithead",
    "titty burgers",
    "titty jelly belly",
    "toad",
    "toady",
    "todger",
    "toe eyed cabbage",
    "toenail",
    "toe-sucker",
    "toilet baby",
    "tomato",
    "tool",
    "toots",
    "tosser",
    "tosspot",
    "trailer trash",
    "traitor",
    "tramp",
    "tranny",
    "transbian",
    "trash",
    "trash bag",
    "tree hugger",
    "tripper",
    "troglodyte",
    "troll",
    "trollface",
    "trolltard",
    "troublemaker",
    "tub of lard",
    "turd",
    "turdball",
    "turdbucket",
    "turd burger",
    "turd burglar",
    "turd cutter",
    "turd hound",
    "turdpile",
    "turkey",
    "twat",
    "twat face",
    "twattock",
    "twatwaffle",
    "twerp",
    "twit",
    "twitter feminist",
    "twunt",
    "tyrant",
    "tyre biter",
    "ugly face",
    "U-Haul lesbian",
    "unclefucker",
    "underperson",
    "unseasoned cabage",
    "urchin",
    "vagina cleaner",
    "vaginal belch",
    "vagina-owner",
    "vampire",
    "vampire bat",
    "vandal",
    "vantz",
    "varmint",
    "vaxhole",
    "vegetable",
    "vermin",
    "vexer",
    "vidiot",
    "vine sucker",
    "Vinnie",
    "vixen",
    "vonce",
    "vulgaris",
    "vulva owner",
    "wacko",
    "wallflower",
    "wally",
    "wanker",
    "wankface",
    "wank stain",
    "wantwit",
    "wart",
    "wasbian",
    "waste",
    "waste of oxygen",
    "wazzock",
    "weakling",
    "weasel",
    "weeaboo",
    "weeb",
    "weed",
    "weeze bag",
    "weirdo",
    "welfare queen",
    "wet",
    "whiner",
    "white rat",
    "whore",
    "whore bag",
    "whorefucker",
    "whore's-bird",
    "whoreson",
    "willy",
    "wimp",
    "windfucker",
    "window licker",
    "windsucker",
    "wino",
    "wit",
    "witch",
    "woketard",
    "womanizer",
    "woman of the evening",
    "wommy",
    "woo woo",
    "worm",
    "wretch",
    "wrongdoer",
    "wuss",
    "xeniatrophobe",
    "xenomaniac",
    "xenomonophobe",
    "xenophile",
    "xenophobe",
    "xyrophobe",
    "yahoo",
    "yampy",
    "yes-man",
    "yeti",
    "yiffer",
    "yonker",
    "yo-yo",
    "yuck",
    "yutz",
    "zebrafucker",
    "zitface",
    "zoophile",
    "zounderkite",
]
